CXXFLAGS := -std=c++20 -fsanitize=address,undefined -g3 -Wall -Wextra

# CXXFLAGS := -std=c++20 -g3
# CXXFLAGS += -fsanitize=address,undefined
# CXXFLAGS += -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC
# CXXFLAGS += -O2 -march=native
# CXXFLAGS += -Wall -Wextra -Wshadow -Wpedantic
# CXXFLAGS += -Wfatal-errors
# CXXFLAGS += -Wconversion -Wno-sign-conversion
# CXXFLAGS += -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference
