site_name: Templatemengo
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: yellow
  features:
    - content.code.annotate
  logo: assets/flamengo.png
  favicon: assets/flamengo.png

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: ['code']
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

