site_name: Templatemengo
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: yellow
  features:
    - content.code.annotate 
  logo: assets/flamengo.png
  favicon: assets/flamengo.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: ['code']
  - admonition
  - pymdownx.details
  - pymdownx.superfences
